[functions]
    directory = "functions"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        
[build]
    publish = "build"

[dev]
    command = "yarn dev"
    publish = "src"
    targetPort = 8080
    framework = "#custom"
