[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        
[build]
    publish = "build"
    command = "yarn build && cd netlify && yarn"

[dev]
    publish = "src"
    command = "yarn dev"
    targetPort = 8080
    framework = "#custom"
