[build]
    publish = "packages/client/build"
    command = "yarn build"

[dev]
    src = "packages/client/src"
    command = "yarn dev:plain"
    targetPort = 8080
    framework = "#custom" 

[functions]
    directory = "packages/server/functions"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 301  # permanent redirect
