[build]
    publish = "build"
    command = "yarn build && cd server && yarn"

[dev]
    publish = "src"
    command = "yarn dev"
    targetPort = 8080
    framework = "#custom" 

[functions]
    directory = "server/functions"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 301  # permanent redirect
