#!/usr/bin/env node
const { exit } = require('process');
const { exec } = require('child_process');

exec('yarn test', (error, stdout, stderr) => {
	if (error || stderr) {
		console.log(`error: ${error.message}`);
		exit(1);
	}

	exit(0);
});
